services:
  postgres:
    image: ramsrib/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_api_db
    ports: 
      - 5432:5432
    networks:
      - rag-api-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - rag-api-network
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    restart: unless-stopped

networks:
  rag-api-network:

volumes:
  postgres_data: