services:
  rag-api:
    build: .
    image: rag-api
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - rag-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge